## observability/tempo/tempo-config.yaml


# This YAML file defines the configuration for Tempo, a distributed tracing backend.
#
# Key sections:
# - server: Sets up HTTP and gRPC ports for Tempo's APIs.
# - distributor: Receives trace data in OTLP format over HTTP/gRPC.
# - compactor: Manages retention and compaction of trace blocks.
# - storage: Defines backend and local path where trace data is stored.
# - overrides: Customizes runtime behavior like enabling metric generation from traces.

server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester: {}

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks

metrics_generator:
  storage:
    path: /tmp/tempo/generator-wal
    remote_write:
      - url: http://prometheus:9090/api/v1/write

  traces_storage:
    path: /tmp/tempo/generator-wal/traces

  registry:
    collection_interval: 15s
    external_labels:
      source: tempo

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]